/* Permissions file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

const permissions = {
	"comments.admin": "Comments administrator (CRUD)",
};

export default permissions;
